import { app } from "@azure/functions";

const BASE="https://api.microservices.signify.com/api/product/v1/smc/pt_PT/search/facets";
const ONOFF=new Set(["PSU","PSU-E","PSUE","PSR"]),DALI=new Set(["PSD","PSD-E","PSDE","PSD-SR","PSD-SRE","DIA","DIA-E","PSED"]);
const U=s=>String(s||"").replace(/\s+/g," ").trim().toUpperCase();
const family=q=>(U(q).match(/\b[A-Z]{1,4}\d{2,4}[A-Z]?\b/)||[])[0]||"";
const driver=q=>U(q).split(/[\s/]+/).find(x=>ONOFF.has(x)||DALI.has(x))||"";
const parse=q=>{let t=U(q).replace(/^\d{12,18}\s*[-:]?\s*/,"").split(/\s+/);let colorToken=t.find(x=>/^\d{3}[A-Z]*$/.test(x))||"";return{family:family(q),driver:driver(q),pack:(t.find(x=>/^(LED)?\d+S$/.test(x))||"").replace(/^LED/,""),cri:colorToken?colorToken[0]:"",cct:colorToken?colorToken.slice(1,3)+"00":"",length:t.find(x=>/^L\d+$/.test(x))||"",optic:t.find(x=>["C","WR","WB","NB","MB","PCS","PCO","PGO"].includes(x))||"",housingColor:t.find(x=>["WH","BK","GR","SI"].includes(x))||""}};
async function getJson(url){try{let r=await fetch(url),text=await r.text();if(!r.ok||!text.trim())return null;return JSON.parse(text)}catch{return null}}
function url(filters,size=10){let u=new URL(BASE);u.searchParams.set("page","1");u.searchParams.set("size",String(size));u.searchParams.set("facets","v:category,v:filter_keys");u.searchParams.set("filters",filters);u.searchParams.set("sort","a:rank");u.searchParams.set("enrichData","true");return u}
const ROOT="filter_keys:FK_LP_TIER_B_BETTER;FK_LP_TIER_C_BEST:ALL,category:SMC_CINDOOR_GR;SMC_OCOUTD_GR:ALL";
async function cat(filters=ROOT,size=10){return getJson(url(filters,size))}
async function quoteSearch(query){const base=process.env.QUOTE_API_BASE,token=process.env.QUOTE_API_TOKEN;if(!base||!token)return null;try{let u=new URL("/api/products/search",base);Object.entries({query,page:0,pageSize:30,configurable:false,language:"en-GB",salesOrganization:"PT02",distributionChannel:"05",soldTo:"null",shipTo:"null"}).forEach(([k,v])=>u.searchParams.set(k,v));let r=await fetch(u,{headers:{Authorization:`Bearer ${token}`,Accept:"application/json"}}),t=await r.text();if(!r.ok||!t.trim())return null;return JSON.parse(t)}catch{return null}}
function attrs(item){let a=Object.fromEntries((item.assignments||[]).map(x=>[x.variableName,U(x.valueName)]));return{family:a.PLM_PFC||a.PLM_PFAM||family(item.description||""),driver:a.PLM_TRAFO||driver(item.description||""),pack:(a.PLM_LAMPFAM||"").replace(/^LED/,""),cct:(a.PLM_COLLAMP||"").slice(0,3),optic:a.PLM_OPTGRP||a.PLM_CVR||"",color:a.PLM_CLR||"",length:(U(item.description||"").match(/\bL\d+\b/)||[])[0]||""}}
function rankSku(p,item,wantDali){let a=attrs(item),score=0,diff=[];if(a.family===p.family)score+=45;let good=wantDali?DALI.has(a.driver):ONOFF.has(a.driver);if(!good)return{score:-999,diff};score+=40;for(const[k,w,g,wt]of[["pack",p.pack,a.pack,30],["cct",p.cct,a.cct,28],["optic",p.optic,a.optic,18],["length",p.length,a.length,18],["color",p.housingColor,a.color,12]]){if(!w)continue;if(w===g)score+=wt;else if(g){score-=Math.round(wt*.7);diff.push(`${k}: ${w} → ${g}`)}}return{score,diff,a}}
function configuratorFrom(items,p){let cfg=[...new Map(items.filter(i=>i.isConfigurable).map(i=>[(U(i.materialName)||U(i.productModelName).split("_")[0]),i])).entries()];if(!cfg.length)return null;let ranked=cfg.map(([name,i])=>({name,item:i,...rankSku(p,i,DALI.has(p.driver)?false:true)})).sort((a,b)=>b.score-a.score);return ranked[0]}
function configDescription(q,newFamily,targetDriver){let out=U(q).replace(/^\d{12,18}\s*[-:]?\s*/,""),old=family(out),d=driver(out);if(old&&newFamily)out=out.replace(new RegExp(`\\b${old}\\b`),newFamily);if(d)out=out.replace(new RegExp(`\\b${d}\\b`),targetDriver);out=out.replace(/\bLED(\d+S)\b/g,"$1").replace(/\/930H\b/g,"/930UE");return out}
function families(j){let m=new Map();for(const f of(j?.facets?.filter_keys||[]))for(const x of(f.data||[])){let z=String(x.value||"").match(/^FK_LP_HOUSING_VARIANT_([A-Z0-9]+)_(.+)$/);if(z&&!m.has(z[1]))m.set(z[1],{family:z[1],raw:z[2],label:z[2].replaceAll("_"," "),count:x.count})}return[...m.values()]}
const fid=f=>`FK_LP_HOUSING_VARIANT_${f.family}_${f.raw}`;
function filterKeys(j,groupId){let g=(j?.dataEnrichment?.filtersData||[]).find(x=>x.id===groupId);return g?.filterKeys||[]}
function exactFilterKey(j,groupId,test){return filterKeys(j,groupId).find(test)?.id||""}
function rangeFilterKey(j,groupId,value){let num=Number(value);if(!num)return"";for(const x of filterKeys(j,groupId)){let m=String(x.displayName||"").match(/(\d+)\s*-\s*(\d+)/);if(m&&num>=Number(m[1])&&num<=Number(m[2]))return x.id}return""}
function technicalKeys(base,p){let out=[];
 if(p.cct){let k=exactFilterKey(base,"FG_LP_COLOR_TEMP",x=>String(x.displayName)===p.cct);if(k)out.push({name:`CCT ${p.cct}K`,key:k,weight:20})}
 if(p.optic){let k=exactFilterKey(base,"FG_LP_LIGHT_DISTRIBUTION",x=>x.id===`FK_LP_LIGHT_DISTRIBUTION_${p.optic}`);if(!k)k=exactFilterKey(base,"FG_LP_OPTICAL_COVER",x=>x.id===`FK_LP_OPTICAL_COVER_${p.optic}`);if(k)out.push({name:p.optic,key:k,weight:16})}
 if(p.length){let k=rangeFilterKey(base,"FG_LP_OVERALL_LENGTH_RANGE",p.length.slice(1));if(k)out.push({name:p.length,key:k,weight:16})}
 if(p.housingColor){let aliases={WH:["WHITE","9003"],BK:["BLACK","9004"],GR:["GREY","GRAY"],SI:["SILVER"]};let k=exactFilterKey(base,"FG_LP_OEM_HOUSING_COLOR",x=>(aliases[p.housingColor]||[p.housingColor]).some(a=>U(x.displayName).includes(a)));if(k)out.push({name:p.housingColor,key:k,weight:10})}
 // Pack token is used as approximate luminous flux when it is numeric, e.g. 50S -> about 5000 lm.
 if(p.pack){let v=Number(p.pack.replace(/S$/,""))*100;let k=rangeFilterKey(base,"FG_LP_LUMFLUX_RANGE",v);if(k)out.push({name:p.pack,key:k,weight:24})}
 return out}
async function countWith(filters){let j=await cat(filters,10);return{json:j,count:j?.meta?.page?.total_results||0}}
function controls(wantDali){return wantDali?"FK_LP_DIMMING_CONTROLS_DALI":"FK_LP_DIMMING_CONTROLS_NO"}
async function progressiveFamilySearch(f,p,wantDali,base){let baseFilters=`filter_keys:${fid(f)}:ALL,filter_keys:${controls(wantDali)}:ALL`;let specs=technicalKeys(base,p);let active=[...specs];let attempts=[];
 while(true){let filters=baseFilters+active.map(x=>`,filter_keys:${x.key}:ALL`).join("");let r=await countWith(filters);attempts.push({criteria:active.map(x=>x.name),count:r.count});if(r.count>0)return{total:r.count,criteria:active.map(x=>x.name),relaxed:specs.filter(x=>!active.includes(x)).map(x=>x.name),filters,json:r.json};if(!active.length)return{total:0,criteria:[],relaxed:specs.map(x=>x.name),filters,json:r.json};let min=Math.min(...active.map(x=>x.weight));active=active.filter(x=>x.weight!==min)} }
async function testFamily(f,p,wantDali,base){let r=await progressiveFamilySearch(f,p,wantDali,base),score=r.total?40:0,reasons=[];if(r.total)reasons.push(`${r.total} produto(s) após filtro técnico`);score+=r.criteria.length*12;reasons.push(...r.criteria.map(x=>`${x} preservado`));if(f.label.includes("LUXSPACE")&&p.family.startsWith("DN")){score+=25;reasons.push("mesma gama LuxSpace")}if(f.label.includes("RECESSED")){score+=12;reasons.push("encastrada")}if(f.label.includes("MINI")){score-=8}return{...f,...r,score,reasons}}
async function rankNew(fs,p,wantDali,base){let pref=p.family.match(/^[A-Z]+/)?.[0]||"";let pool=fs.filter(x=>x.family!==p.family&&(x.family.startsWith(pref)||x.label.includes("LUXSPACE"))).slice(0,30),a=[];for(const f of pool)a.push(await testFamily(f,p,wantDali,base));return a.filter(x=>x.total>0).sort((x,y)=>y.score-x.score)}
async function engine(q){let p=parse(q),base=await cat();if(!base)return{status:"SOURCE UNAVAILABLE",message:"O catálogo Signify não respondeu. Nenhuma referência foi criada."};if(!p.family)return{status:"NEEDS REVIEW",message:"Família não identificada."};if(!p.driver)return{status:"NEEDS REVIEW",message:"Driver PSU/PSD não identificado."};let fs=families(base),cur=fs.find(x=>x.family===p.family),wantDali=ONOFF.has(p.driver);
 if(cur){let targetDriver=wantDali?"PSD":"PSU",ideal=U(q).replace(new RegExp(`\\b${p.driver}\\b`),targetDriver);let live=await quoteSearch(ideal);if(live?.items?.length){let ranked=live.items.map(i=>({i,...rankSku(p,i,wantDali)})).filter(x=>x.score>-900).sort((a,b)=>b.score-a.score);let best=ranked[0];if(best&&best.score>=130)return{status:"VERIFIED STANDARD MATCH",currentFamily:cur.family,familyLabel:cur.label,target:wantDali?"DALI / PSD":"ON/OFF / PSU",recommended:best.i.description,orderCode:(best.i.externalId||"").replace(/^0+/,""),differences:best.diff,message:"Produto standard validado na fonte de produto."};let cfg=configuratorFrom(live.items,p);if(cfg){let aa=attrs(cfg.item),td=wantDali?(aa.driver?.endsWith("-E")?"PSD-E":"PSD"):"PSU";return{status:"CONFIGURATOR MATCH",currentFamily:aa.family||cur.family,familyLabel:cur.label,configurator:cfg.name,recommended:configDescription(q,aa.family||cur.family,td),orderCode:null,target:wantDali?"DALI / PSD":"ON/OFF / PSU",message:"O configurador oferece uma correspondência melhor do que os SKUs standard. A configuração deve ser finalizada/validada no configurador; não é inventado 12NC."}}}let r=await testFamily(cur,p,wantDali,base);return{status:r.total?"FILTERED ALTERNATIVES FOUND":"NO VERIFIED ALTERNATIVE",currentFamily:cur.family,familyLabel:cur.label,target:wantDali?"DALI / PSD":"ON/OFF / PSU",totalCompatible:r.total,matchedCriteria:r.criteria,relaxedCriteria:r.relaxed,reasons:r.reasons,message:r.total?`A pesquisa foi reduzida de toda a família para ${r.total} resultado(s), preservando os critérios disponíveis no catálogo. A descrição/12NC só será mostrada quando dispusermos do endpoint de resultados de produto, porque esta API de facets não devolve SKUs.`:"Nenhum produto foi confirmado mesmo após relaxamento progressivo dos filtros técnicos."}}
 let ranked=await rankNew(fs,p,wantDali,base),b=ranked[0];if(!b)return{status:"OLD / NON-CURRENT FAMILY",oldFamily:p.family,message:"Família antiga, sem família atual tecnicamente confirmada."};let second=ranked[1],conf=!second||b.score-second.score>=10;if(conf){let targetDriver=wantDali?"PSD-E":"PSU-E",probe=configDescription(q,b.family,targetDriver),live=await quoteSearch(probe);if(live?.items?.length){let sku=live.items.map(i=>({i,...rankSku({...p,family:b.family},i,wantDali)})).filter(x=>x.score>-900).sort((a,b)=>b.score-a.score)[0];if(sku&&sku.score>=130)return{status:"VERIFIED STANDARD MATCH",oldFamily:p.family,currentFamily:b.family,familyLabel:b.label,recommended:sku.i.description,orderCode:(sku.i.externalId||"").replace(/^0+/,""),differences:sku.diff,target:wantDali?"DALI / PSD":"ON/OFF / PSU",message:"Família atual e produto standard validados."};let cfg=configuratorFrom(live.items,{...p,family:b.family});if(cfg){let aa=attrs(cfg.item),td=wantDali?(aa.driver?.endsWith("-E")?"PSD-E":"PSD"):"PSU-E";return{status:"NEW-FAMILY CONFIGURATOR MATCH",oldFamily:p.family,currentFamily:aa.family||b.family,familyLabel:b.label,configurator:cfg.name,recommended:configDescription(q,aa.family||b.family,td),orderCode:null,target:wantDali?"DALI / PSD":"ON/OFF / PSU",message:"A família antiga foi substituída por uma família atual configurável. O configurador preserva melhor as características do que os SKUs standard; o 12NC final é gerado/confirmado no configurador."}}}}return{status:conf?"CURRENT FAMILY MATCH FOUND":"CURRENT FAMILY CANDIDATE",oldFamily:p.family,currentFamily:b.family,familyLabel:b.label,target:wantDali?"DALI / PSD":"ON/OFF / PSU",totalCompatible:b.total,matchedCriteria:b.criteria,relaxedCriteria:b.relaxed,reasons:b.reasons,confidence:conf?"HIGH":"REVIEW",message:conf?`A melhor família atual foi selecionada e refinada para ${b.total} resultado(s) com os critérios técnicos disponíveis. A descrição/12NC permanece bloqueada até o endpoint devolver os SKUs reais.`:"Existe mais de uma família próxima. É necessária validação adicional antes de assumir a migração."}}
app.http("alternative",{methods:["GET","POST"],authLevel:"anonymous",handler:async req=>{if(req.method==="GET")return{jsonBody:{status:"OK",mode:"technical-filter-v3"}};let b;try{b=await req.json()}catch{return{status:400,jsonBody:{status:"ERROR",message:"JSON inválido"}}}return{jsonBody:await engine(b?.query||"")}}});
