import { app } from "@azure/functions";

const PRODUCT_BASE="https://api.microservices.signify.com/api/product/v1/smc/pt_PT/search/facets";
const ONOFF=new Set(["PSU","PSU-E","PSUE","PSR"]),DALI=new Set(["PSD","PSD-E","PSDE","PSD-SR","PSD-SRE","DIA","DIA-E","PSED"]);
const n=s=>String(s||"").replace(/\s+/g," ").trim().toUpperCase();
const family=q=>(n(q).match(/\b[A-Z]{1,4}\d{2,4}[A-Z]?\b/)||[])[0]||"";
const driver=q=>n(q).split(/[\s/]+/).find(x=>ONOFF.has(x)||DALI.has(x))||"";
const targetDali=d=>ONOFF.has(d), targetOnOff=d=>DALI.has(d);
async function jsonFetch(url,opts={}){try{let r=await fetch(url,opts),t=await r.text();if(!r.ok||!t.trim())return null;return JSON.parse(t)}catch{return null}}
function familyFacets(j){let all=[];for(const f of (j?.facets?.filter_keys||[])){for(const x of (f.data||[])){let m=String(x.value||"").match(/^FK_LP_HOUSING_VARIANT_([A-Z0-9]+)_(.+)$/);if(m)all.push({family:m[1],label:m[2].replaceAll("_"," "),count:x.count})}}return all}
async function catalog(filters=""){let u=new URL(PRODUCT_BASE);u.searchParams.set("page","1");u.searchParams.set("size","10");u.searchParams.set("facets","v:category,v:filter_keys");u.searchParams.set("filters",filters||"filter_keys:FK_LP_TIER_B_BETTER;FK_LP_TIER_C_BEST:ALL,category:SMC_CINDOOR_GR;SMC_OCOUTD_GR:ALL");u.searchParams.set("sort","a:rank");u.searchParams.set("enrichData","true");return jsonFetch(u)}
function currentFamily(fs,f){return fs.find(x=>x.family===f)}
function productWords(q){return new Set(n(q).replace(/\b\d{12,18}\b/g,"").split(/[\s/\-_]+/).filter(Boolean))}
function successorCandidates(fs,q){let f=family(q),prefix=f.match(/^[A-Z]+/)?.[0]||"",num=Number(f.match(/\d+/)?.[0]||0);return fs.filter(x=>x.family!==f).map(x=>{let xn=Number(x.family.match(/\d+/)?.[0]||0), xp=x.family.match(/^[A-Z]+/)?.[0]||"";let s=0;if(xp===prefix)s+=20;if(num&&xn)s+=Math.max(0,15-Math.abs(xn-num)/10);let qw=productWords(q);for(const w of qw)if(x.label.includes(w))s+=4;if(f.startsWith("DN")&&x.label.includes("LUXSPACE"))s+=20;return{...x,score:s}}).filter(x=>x.score>5).sort((a,b)=>b.score-a.score).slice(0,8)}
async function engine(q){let base=await catalog();if(!base)return{status:"SOURCE UNAVAILABLE",recommended:null,message:"A fonte oficial do catálogo não respondeu. Nenhuma referência será inventada."};let fs=familyFacets(base),f=family(q),d=driver(q);if(!f)return{status:"NEEDS REVIEW",recommended:null,message:"Não foi possível identificar a família na referência."};let cur=currentFamily(fs,f);
 // Existing family: use official facets to verify the family is current and verify DALI availability before searching a concrete output.
 if(cur){let needDali=targetDali(d),flt=`filter_keys:FK_LP_HOUSING_VARIANT_${cur.family}_${cur.label.replaceAll(" ","_")}:ALL${needDali?",filter_keys:FK_LP_DIMMING_CONTROLS_DALI:ALL":""}`;let scoped=await catalog(flt);let total=scoped?.meta?.page?.total_results||0;return{status:"CURRENT FAMILY VERIFIED",recommended:null,currentFamily:cur.family,familyLabel:cur.label,totalCompatible:total,message:total?`Família atual confirmada no catálogo oficial. Existem ${total} resultados compatíveis com o filtro solicitado, mas a app ainda não mostra uma referência concreta sem validação SKU/configurador.`:"Família atual confirmada, mas nenhuma alternativa com o filtro DALI foi validada nesta pesquisa."}}
 // Old/non-current family: discover current candidates dynamically, but never call one a successor until configurator/product validation proves it.
 let cand=successorCandidates(fs,q);return{status:"OLD / NON-CURRENT FAMILY",recommended:null,oldFamily:f,currentFamilyCandidates:cand,message:cand.length?"A família original não aparece no catálogo atual. Foram encontrados candidatos atuais para validação, mas nenhum é apresentado como sucessor sem confirmação do configurador.":"A família original não aparece no catálogo atual e não foi possível validar uma família sucessora."}}
app.http("alternative",{methods:["GET","POST"],authLevel:"anonymous",handler:async(req)=>{if(req.method==="GET")return{jsonBody:{status:"OK",source:"Signify product microservice",mode:"verified-only"}};let b;try{b=await req.json()}catch{return{status:400,jsonBody:{status:"ERROR",message:"JSON inválido"}}}return{jsonBody:await engine(b?.query||"")}}});
