import { app } from "@azure/functions";
const API="https://api.microservices.signify.com/api/product/v1/smc/pt_PT/search",FACETS=API+"/facets";
const ONOFF=new Set(["PSU","PSU-E","PSUE","PSR"]),DALI=new Set(["PSD","PSD-E","PSDE","PSD-SR","PSD-SRE","DIA","DIA-E","PSED"]),U=s=>String(s||"").replace(/\s+/g," ").trim().toUpperCase(),V=(o,k)=>o?.[k]?.value;
function parse(q){let raw=U(q).replace(/^\d{8,18}\s*[-:]?\s*/,""),t=raw.split(/\s+/),cc=t.find(x=>/^\d{3}[A-Z]*$/.test(x))||"";return{raw,family:(raw.match(/\b[A-Z]{1,4}\d{2,4}[A-Z]?\b/)||[])[0]||"",driver:t.find(x=>ONOFF.has(x)||DALI.has(x))||"",pack:(t.find(x=>/^(?:LED)?\d+S$/.test(x))||"").replace(/^LED/,""),cct:cc?cc.slice(1,3)+"00":"",length:t.find(x=>/^L\d+$/.test(x))||"",generation:t.find(x=>/^G\d+$/.test(x))||"",tokens:new Set(t)}}
async function J(u){try{let r=await fetch(u),t=await r.text();if(!r.ok||!t.trim())return null;return JSON.parse(t)}catch{return null}}
function url(base,filters,size=100){let u=new URL(base);Object.entries({page:1,size,facets:"v:filter_keys,v:family_id,v:category",filters,sort:"a:sku",enrichData:"true"}).forEach(([k,v])=>u.searchParams.set(k,v));return u}
const ROOT="filter_keys:FK_LP_TIER_B_BETTER;FK_LP_TIER_C_BEST:ALL,category:SMC_CINDOOR_GR;SMC_OCOUTD_GR:ALL,type:Normal;SemiConfigured:ALL";
async function discovery(){return J(url(FACETS,ROOT,10))}function fams(j){return j?.dataEnrichment?.familyData||[]}function famByCode(j,c){return fams(j).find(f=>U(f.id).includes(`_${c}_`))}
async function products(fid,dali){let ctrl=dali?"FK_LP_DIMMING_CONTROLS_DALI":"FK_LP_DIMMING_CONTROLS_NO";return J(url(API,`family_id:${fid}:ALL,type:Normal;SemiConfigured:ALL,filter_keys:${ctrl}:ALL`,100))}
function attrs(i){let name=U(V(i,"name")||""),t=name.split(/\s+/),cc=t.find(x=>/^\d{3}[A-Z]*$/.test(x))||"",fv=V(i,"filter_values")||[],flux=0;for(const s of fv)if(s.startsWith("FG_LP_LUMFLUX_RANGE:"))flux=Number(s.split(":")[1].trim().replace(".","").replace(",","."));return{name,pack:(t.find(x=>/^(?:LED)?\d+S$/.test(x))||"").replace(/^LED/,""),cct:cc?cc.slice(1,3)+"00":"",length:(name.match(/\bL\d+\b/)||[])[0]||"",generation:(name.match(/\bG\d+\b/)||[])[0]||"",flux,keys:new Set(V(i,"filter_keys")||[]),sku:V(i,"sku")||"",configurator:V(i,"configurator_id")||"",url:V(i,"url")||""}}
function rank(p,i){let a=attrs(i),dali=ONOFF.has(p.driver),score=0,d=[];if(a.keys.has("FK_LP_DIMMING_CONTROLS_DALI")!==dali)return{score:-999,a,d};if(a.name.includes(p.family))score+=60;score+=55;if(p.generation){if(a.generation===p.generation)score+=25;else if(a.generation){score-=12;d.push(`generation: ${p.generation} -> ${a.generation}`)}}if(p.pack===a.pack)score+=50;else if(p.pack){let want=Number(p.pack.replace(/S/,""))*100,act=a.flux||Number((a.pack.match(/\d+/)||[])[0]||0)*100,pct=act&&want?Math.abs(act-want)/want:1;score+=Math.max(-35,35-pct*100);d.push(`pack: ${p.pack} -> ${a.pack||act+'lm'}`)}if(p.cct===a.cct)score+=35;else if(p.cct&&a.cct){score-=25;d.push(`CCT: ${p.cct} -> ${a.cct}`)}if(p.length===a.length)score+=32;else if(p.length&&a.length){score-=25;d.push(`length: ${p.length} -> ${a.length}`)}for(const x of p.tokens)if(![p.family,p.driver,p.pack,p.generation].includes(x)&&!/^\d{3}/.test(x)&&!/^L\d+/.test(x)&&a.name.includes(x))score+=8;return{score,a,d,item:i}}
const R=x=>({description:V(x.item,"name"),sku:x.a.sku,url:x.a.url,configurator:x.a.configurator,score:Math.round(x.score),differences:x.d});
async function searchFamily(f,p,dali){let j=await products(f.id,dali),ranked=(j?.results||[]).map(i=>rank(p,i)).filter(x=>x.score>-900).sort((a,b)=>b.score-a.score);return{j,ranked,top:ranked.slice(0,2)}}
function sim(p,f){let n=U(f.familyName),id=U(f.id),s=0;if(id.includes(`_${p.family}_`))s+=100;if(p.family.startsWith("DN")&&n.includes("LUXSPACE"))s+=45;if(n.includes("COMPACT")&&/DN57/.test(p.family))s+=30;if(n.includes("MINI")&&/DN57/.test(p.family))s-=18;return s}
async function current(root,p,dali){let c=fams(root).map(f=>({f,b:sim(p,f)})).filter(x=>x.b>0).sort((a,b)=>b.b-a.b).slice(0,12),out=[];for(const x of c){let s=await searchFamily(x.f,p,dali);if(s.ranked.length)out.push({...x,...s,best:x.b+s.ranked[0].score})}return out.sort((a,b)=>b.best-a.best)}
async function engine(q){let p=parse(q);if(!p.family||!p.driver)return{status:"NEEDS REVIEW",message:"Família/driver não reconhecido."};let root=await discovery();if(!root)return{status:"SOURCE UNAVAILABLE",message:"A pesquisa Signify não respondeu."};let dali=ONOFF.has(p.driver),f=famByCode(root,p.family);if(f){let s=await searchFamily(f,p,dali);if(!s.top.length)return{status:"NO VERIFIED ALTERNATIVE",currentFamily:p.family,message:"Nenhum produto com controlo alternativo foi devolvido pela Signify."};let b=s.top[0],r=R(b),strong=b.score>=190;return{status:strong?"VERIFIED STANDARD MATCH":"CLOSEST VERIFIED MATCH",currentFamily:p.family,recommended:r.description,orderCode:r.sku,productUrl:r.url,configurator:r.configurator||null,score:r.score,differences:r.differences,alternatives:s.top[1]?[R(s.top[1])]:[],message:"Resultado baseado em SKUs reais devolvidos pelo endpoint /search da Signify."}}
 let c=await current(root,p,dali);if(!c.length)return{status:"OLD / NON-CURRENT FAMILY",oldFamily:p.family,message:"Nenhuma família atual compatível foi confirmada."};let b=c[0],runner=c[1],code=(U(b.f.id).match(/LP_CF_([A-Z0-9]+)_/)||[])[1]||b.f.familyName,strong=!runner||b.best-runner.best>=15,sku=b.ranked[0];if(sku.score>=190){let r=R(sku);return{status:"VERIFIED NEW-FAMILY STANDARD MATCH",oldFamily:p.family,currentFamily:code,recommended:r.description,orderCode:r.sku,productUrl:r.url,differences:r.differences,score:r.score,message:"Nova família e SKU standard validados na pesquisa Signify."}}let cfg=b.ranked.map(x=>x.a.configurator).find(Boolean);if(cfg&&strong)return{status:"NEW-FAMILY CONFIGURATOR REQUIRED",oldFamily:p.family,currentFamily:code,configurator:cfg,criteria:[p.pack,p.cct,p.length,...[...p.tokens].filter(x=>["C","WR","WB","PCS","PCO","PGO","WH","BK","GR"].includes(x))].filter(Boolean),message:"Os SKUs standard não preservam suficientemente os critérios. Use o configurador indicado, mantendo estes critérios e trocando apenas PSU ↔ DALI. A configuração final não é fabricada pelo site."};return{status:"CURRENT FAMILY CANDIDATE",oldFamily:p.family,currentFamily:code,confidence:strong?"HIGH":"REVIEW",message:"Família atual provável, mas requer validação adicional."}}
app.http("alternative",{methods:["GET","POST"],authLevel:"anonymous",handler:async req=>{if(req.method==="GET")return{jsonBody:{status:"OK",mode:"product-search-v5"}};let b;try{b=await req.json()}catch{return{status:400,jsonBody:{status:"ERROR",message:"JSON inválido"}}}return{jsonBody:await engine(b?.query||"")}}});
